"""followers

Revision ID: 063574dd443a
Revises: cde4ba16296a
Create Date: 2023-12-20 15:23:45.699489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063574dd443a'
down_revision = 'cde4ba16296a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
